# typed: false
# frozen_string_literal: true

# Originally generated by GoReleaser. No longer regenerated: the project is now
# released as `varve`, so GoReleaser writes Formula/varve.rb and never touches
# this file again. Hand-maintained from here.
#
# Kept, and kept accurate, on purpose. These artifacts are real: memtrace v1.5.4
# under MIT, and the binary inside each tarball is named `memtrace` — so the URLs,
# checksums, license and `bin.install` below must stay as they are. GitHub
# 301-redirects the memtrace-dev release URLs to varve-sh/varve, so existing
# installs keep working.
#
# Deleting this would break `brew upgrade` for anyone who installed memtrace.
# The cutover is documented in README.md and happens with the first varve release.
class Memtrace < Formula
  desc "Local-first memory engine for AI coding agents"
  homepage "https://varve.sh"
  version "1.5.4"
  license "MIT"

  # Renamed to `varve` (2026-07-29). Existing installs keep working; new ones
  # should use `brew install varve-sh/tap/varve`.
  deprecate! date: "2026-07-29", because: "it was renamed to `varve`"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/memtrace-dev/memtrace/releases/download/v1.5.4/memtrace_1.5.4_darwin_amd64.tar.gz"
      sha256 "bdfcedb2750962f3dee36039e8d39d70221569e02ad9e0bf98f7f6fc5401e194"

      define_method(:install) do
        bin.install "memtrace"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/memtrace-dev/memtrace/releases/download/v1.5.4/memtrace_1.5.4_darwin_arm64.tar.gz"
      sha256 "1d204566461d5cdb7b5f40a4576b0e818dc65153999629924478efc950cd53be"

      define_method(:install) do
        bin.install "memtrace"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/memtrace-dev/memtrace/releases/download/v1.5.4/memtrace_1.5.4_linux_amd64.tar.gz"
      sha256 "eae9bd6152a1cb605a28d03000dac1951959402addf1a3e3b1b8c6fdf6f3031d"
      define_method(:install) do
        bin.install "memtrace"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/memtrace-dev/memtrace/releases/download/v1.5.4/memtrace_1.5.4_linux_arm64.tar.gz"
      sha256 "8d40a675f82d04d4ab6b35428c584a9f711449eec88689d7de9674064e021924"
      define_method(:install) do
        bin.install "memtrace"
      end
    end
  end

  test do
    system "#{bin}/memtrace", "--version"
  end
end
