# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Memtrace < Formula
  desc "Local-first memory engine for AI coding agents"
  homepage "https://memtrace.sh"
  version "1.5.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/memtrace-dev/memtrace/releases/download/v1.5.2/memtrace_1.5.2_darwin_amd64.tar.gz"
      sha256 "59762e42f0fe6cb5bd9c08d4731606bde584ee4b7186da99274d747751f049a7"

      define_method(:install) do
        bin.install "memtrace"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/memtrace-dev/memtrace/releases/download/v1.5.2/memtrace_1.5.2_darwin_arm64.tar.gz"
      sha256 "7896ba8f32b421faecdd2d29a342f8d5be80d2c23dfd14f34ab9c40bd8d9f30c"

      define_method(:install) do
        bin.install "memtrace"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/memtrace-dev/memtrace/releases/download/v1.5.2/memtrace_1.5.2_linux_amd64.tar.gz"
      sha256 "6701cb2461045827980f17d20f52584015cbbb59ba142da936ed2e2d9f3e11bd"
      define_method(:install) do
        bin.install "memtrace"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/memtrace-dev/memtrace/releases/download/v1.5.2/memtrace_1.5.2_linux_arm64.tar.gz"
      sha256 "b8ff37eecec687090a44c448244fb5dc094ca8168901e4900cfff21a29325efd"
      define_method(:install) do
        bin.install "memtrace"
      end
    end
  end

  test do
    system "#{bin}/memtrace", "--version"
  end
end
