# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Memtrace < Formula
  desc "Local-first memory engine for AI coding agents"
  homepage "https://memtrace.sh"
  version "1.5.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/memtrace-dev/memtrace/releases/download/v1.5.1/memtrace_1.5.1_darwin_amd64.tar.gz"
      sha256 "42be37df029c11fa570e117a1f6a0cae7ad89d721fd90b588ff0ef96d359e370"

      define_method(:install) do
        bin.install "memtrace"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/memtrace-dev/memtrace/releases/download/v1.5.1/memtrace_1.5.1_darwin_arm64.tar.gz"
      sha256 "13658b242a0dd9629305e39e7cb61537fc731d8798a3b25028fe98fb9938d1a5"

      define_method(:install) do
        bin.install "memtrace"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/memtrace-dev/memtrace/releases/download/v1.5.1/memtrace_1.5.1_linux_amd64.tar.gz"
      sha256 "50ce70e5d54d7beb1d0379e162d12a7582f65011988f4d5416144ef4965fc5bb"
      define_method(:install) do
        bin.install "memtrace"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/memtrace-dev/memtrace/releases/download/v1.5.1/memtrace_1.5.1_linux_arm64.tar.gz"
      sha256 "db36ebbac00ed9ca641da5ef4e35994af7f9a8d930b25606d96681e892326e62"
      define_method(:install) do
        bin.install "memtrace"
      end
    end
  end

  test do
    system "#{bin}/memtrace", "--version"
  end
end
