# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Varve < Formula
  desc "Decision memory for AI coding agents — local-first, MCP-native, one binary"
  homepage "https://varve.sh"
  version "2.0.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/varve-sh/varve/releases/download/v2.0.0/varve_2.0.0_darwin_amd64.tar.gz"
      sha256 "aba318ba3c38a90bb395b08b342e5de1c762c69d2f4f513fdf1ab7ae88f88f10"

      define_method(:install) do
        bin.install "varve"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/varve-sh/varve/releases/download/v2.0.0/varve_2.0.0_darwin_arm64.tar.gz"
      sha256 "a1b72deb4237f2db916e25fb10b7109b4ca2ea322e37118b5af52d0c22ed027f"

      define_method(:install) do
        bin.install "varve"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/varve-sh/varve/releases/download/v2.0.0/varve_2.0.0_linux_amd64.tar.gz"
      sha256 "3256459716da889585525f191a5d60f21257d2ce99fa1c0d32853451ff0e2481"
      define_method(:install) do
        bin.install "varve"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/varve-sh/varve/releases/download/v2.0.0/varve_2.0.0_linux_arm64.tar.gz"
      sha256 "6377cba3aa47d01e7ca74e3c002e335e80162f7d4e8dd93f4a95454069a37e69"
      define_method(:install) do
        bin.install "varve"
      end
    end
  end

  test do
    system "#{bin}/varve", "--version"
  end
end
