# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Varve < Formula
  desc "Decision memory for AI coding agents — local-first, MCP-native, one binary"
  homepage "https://varve.sh"
  version "2.0.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/varve-sh/varve/releases/download/v2.0.2/varve_2.0.2_darwin_amd64.tar.gz"
      sha256 "de3b9ab035bf95afe51f07a44c0247fa89f16d42d59a0937d3a244509555ef9a"

      define_method(:install) do
        bin.install "varve"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/varve-sh/varve/releases/download/v2.0.2/varve_2.0.2_darwin_arm64.tar.gz"
      sha256 "1e09ebd1d27def698c3df81d7d109cec0b6edc603189524af8f778d3e2848cc2"

      define_method(:install) do
        bin.install "varve"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/varve-sh/varve/releases/download/v2.0.2/varve_2.0.2_linux_amd64.tar.gz"
      sha256 "d118be115fd96d01c9a240bdfdb6965dc075e2ad62cfcf9e1a9b365b7f11224f"
      define_method(:install) do
        bin.install "varve"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/varve-sh/varve/releases/download/v2.0.2/varve_2.0.2_linux_arm64.tar.gz"
      sha256 "94ce714b81dcb9701bc6cd2d3826c049faeb8413bf8d08c775075033a69ff37a"
      define_method(:install) do
        bin.install "varve"
      end
    end
  end

  test do
    system "#{bin}/varve", "--version"
  end
end
